export enum SocketEvents {
    // Chat
    SendMessage = 'sendMessage',
    CreateChatRoom = 'createChatRoom',
    DeleteChatRoom = 'deleteChatRoom',
    JoinChatRoom = 'joinChatRoom',
    LeaveChatRoom = 'leaveChatRoom',
    JoinChatRoomSession = 'joinChatRoomSession',
    LeaveChatRoomSession = 'leaveChatRoomSession',
    GetAllChatRooms = 'getAllChatRooms',

    // Chat error
    CreateChatRoomError = 'createChatRoomError',
    DeleteChatRoomNotFoundError = 'deleteChatRoomNotFoundError',
    DeleteChatNotCreatorError = 'deleteChatNotCreatorError',
    JoinChatRoomNotFoundError = 'joinChatRoomNotFoundError',
    LeaveChatRoomNotFoundError = 'leaveChatRoomNotFoundError',
    JoinChatRoomSessionNotFoundError = 'JoinChatRoomSessionNotFoundError',
    LeaveChatRoomSessionNotFoundError = 'leaveChatRoomSessionNotFoundError',
    SendMessageError = 'sendMessageError',

    // ReceiveHomeMessage = 'broadcastMessageHome',
    // JoinHomeRoom = 'joinHomeRoom',
    // UserJoinedRoom = 'userJoinedRoom',
    // UserConnected = 'userConnected',
    // SendHomeMessage = 'sendHomeMessage',
    // UserLeftRoom = 'leaveHomeRoom',
    // RoomIsFull = 'roomIsFull',
    // UsernameTaken = 'usernameTaken',
    // UserLeftHomeRoom = 'userLeftHomeRoom',
    Disconnect = 'disconnect',
    SignIn = 'signIn',
    SignOut = 'signOut',

    // GameRoom commands
    CreateWaitingRoom = 'createGame',
    JoinWaitingRoom = 'roomJoin',
    UpdateWaitingRoom = 'gameCreatedConfirmation',
    ExitWaitingRoom = 'exitWaitingRoom', // Used to tell a user is leaving the room
    JoinedValidWaitingRoom = 'joinValid',
    UpdateGameRooms = 'updateListOfRooms',
    PlayerJoinedWaitingRoom = 'foundOpponent',
    ErrorJoining = 'joiningError',
    EnterRoomLobby = 'roomLobby',
    KickedFromGameRoom = 'kickedFromGameRoom',
    GameAboutToStart = 'gameAboutToStart',
    OpponentLeave = 'opponentLeave',
    StartScrabbleGame = 'startScrabbleGame',

    Invite = 'invite',
    GameMessage = 'gameMessage',
    GameCommand = 'command',
    OpponentDisconnect = 'user disconnect',
    UpdateGameBoard = 'updateGameBoard',
    RackViewUpdate = 'updateRackClient',
    UpdatePlayersInformation = 'UpdateMyPlayerInformation',
    UpdateOpponentInformation = 'UpdateOpponentInformation',
    TimerClientUpdate = 'timerUpdate',
    OpponentGameLeave = 'OpponentLeftTheGame',
    GameEnd = 'endGame',
    AbandonGame = 'AbandonGame',
    LetterReserveUpdated = 'letterReserveUpdated',
    UserDisconnect = 'user disconnect',
    ImportDictionary = 'ImportDictionary',
    SendMessageHome = 'sendMessageHome',
    JoinAsObserver = 'joinAsObserver',
    CannotReplaceBot = 'cannotReplaceBot',
    // Client game calls
    PlaceWordCommand = 'placeWord',
    Exchange = 'ExchangeLetters',
    Skip = 'skip',
    QuitGame = 'quitGame',
    ReserveCommand = 'reserveCommand',
    ClueCommand = 'clueCommand',
    // Server game feedback calls (Server -> Clients)
    PublicViewUpdate = 'updateClientView',
    AllReserveLetters = 'allReserveLetters',
    NextTurn = 'nextTurn',
    PlacementSuccess = 'placementSuccess',
    PlacementFailure = 'placementFailure',
    ExchangeSuccess = 'ExchangeSuccess',
    ExchangeFailure = 'ExchangeFailure',
    UserAlreadyConnected = 'UserAlreadyConnected',
    SuccessfulConnection = 'SuccessfulConnection',

    // Synchrous games UI
    SendDrag = 'sd',
    DragEvent = 'de',
    LetterPlaced = 'lp',
    LetterTaken = 'lt',
}
