export enum SocketEvents {
    // Methods used for the prototype
    SendMessage = 'sendMessage',
    ReceiveHomeMessage = 'broadcastMessageHome',
    JoinHomeRoom = 'joinHomeRoom',
    UserJoinedRoom = 'userJoinedRoom',
    UserConnected = 'userConnected',
    SendHomeMessage = 'sendHomeMessage',
    UserLeftRoom = 'leaveHomeRoom',
    RoomIsFull = 'roomIsFull',
    UsernameTaken = 'usernameTaken',
    UserLeftHomeRoom = 'userLeftHomeRoom',
    Disconnect = 'disconnect',
    SignIn = 'signIn',
    SignOut = 'signOut',

    // GameRoom commands
    CreateWaitingRoom = 'createGame',
    JoinWaitingRoom = 'roomJoin',
    UpdateWaitingRoom = 'gameCreatedConfirmation',
    ExitWaitingRoom = 'exitWaitingRoom', // Used to tell a user is leaving the room
    JoinedValidWaitingRoom = 'joinValid',
    UpdateGameRooms = 'updateListOfRooms',
    PlayerJoinedWaitingRoom = 'foundOpponent',
    ErrorJoining = 'joiningError',
    EnterRoomLobby = 'roomLobby',
    KickedFromGameRoom = 'kickedFromGameRoom',
    GameAboutToStart = 'gameAboutToStart',
    OpponentLeave = 'opponentLeave',
    StartScrabbleGame = 'startScrabbleGame',

    Invite = 'invite',
    GameMessage = 'gameMessage',
    GameCommand = 'command',
    OpponentDisconnect = 'user disconnect',
    PublicViewUpdate = 'updateClientView',
    UpdateGameBoard = 'updateGameBoard',
    Play = 'playGame',
    Exchange = 'ExchangeLetters',
    RackViewUpdate = 'updateRackClient',
    Skip = 'skip',
    UpdatePlayerInformation = 'UpdateMyPlayerInformation',
    UpdateOpponentInformation = 'UpdateOpponentInformation',
    CreateScrabbleGame = 'createScrabbleGame',
    TimerClientUpdate = 'timerUpdate',
    OpponentGameLeave = 'OpponentLeftTheGame',
    GameEnd = 'endGame',
    AbandonGame = 'AbandonGame',
    LetterReserveUpdated = 'letterReserveUpdated',
    ImpossibleCommandError = 'impossibleCommandError',
    UserDisconnect = 'user disconnect',
    QuitGame = 'quitGame',
    ReserveCommand = 'reserveCommand',
    AllReserveLetters = 'allReserveLetters',
    ClueCommand = 'clueCommand',
    ImportDictionary = 'ImportDictionary',
    SendMessageHome = 'sendMessageHome',
}
