/* eslint-disable max-len */
export const SECRET_KEY =
    'eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY3NzUzMTA2MywiaWF0IjoxNjc3NTMxMDYzfQ.nOalpfiUeeZOhWgCjhyeV1qdVZbE4HdM0btdrA6zlB8';
